### ISSUE TITLE
Instant run-off voting :)

### ISSUE THREAD

**Issue by BCSol** [stustanet/wahlfang#1]
Online votes are time consuming when additional run-offs are needed.
If instant run-off voting would be supported, this process can be shortened to exactly one voting, while having the benefits of a reduced spoiler effect.

**Comment by juelg** [comment]
Hi Balthasar,
thank you for your input.
We already have a generalization of this method which is called single-transferable vote as an issue on our [gitlab repo](https://gitlab.stusta.de/stustanet/wahlfang/-/issues/19). We will have to decide how we handle issues in the future. But for now (since you have an account on our gitlab anyway) please feel free to comment your ideas over at the issue on our gitlab. Thanks.
